export const HOOKS = {
  STORE: 'useStore',
  STATE: 'useState',
  CONTEXT: 'useContext',
  REF: 'useRef',
  DEFAULT_PROPS: 'useDefaultProps',
  STYLE: 'useStyle',
  TARGET: 'useTarget',
  METADATA: 'useMetadata',
  MOUNT: 'onMount',
  EVENT: 'onEvent',
  UNMOUNT: 'onUnMount',
  UPDATE: 'onUpdate',
  INIT: 'onInit',
  SET_CONTEXT: 'setContext',
} as const;
