enableGlobalCache: true

# `pnp` causes tons of type errors in `core`.
nodeLinker: node-modules

# CLI project can't find `@builder.io/mitosis` imports without this.
nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
