export const REACT_ATTRIBUTE_MAPPING: Record<string, string> = {
  htmlFor: 'for',
  className: 'class',
};

export const REACT_ELEMENT_ATTRIBUTE_MAPPING: Record<
  string,
  Record<string, string>
> = {
  input: {
    defaultChecked: 'checked',
    defaultValue: 'value',
  },
};

// Reference: https://developer.mozilla.org/en-US/docs/Web/SVG/Element#SVG_elements
// https://github.com/reactjs/react-magic/blob/master/src/htmltojsx.js
export const REACT_ELEMENT_TAG_NAME_MAPPING: Record<string, string> = {
  a: 'a',
  altGlyph: 'altglyph',
  altGlyphDef: 'altglyphdef',
  altGlyphItem: 'altglyphitem',
  animate: 'animate',
  animateColor: 'animatecolor',
  animateMotion: 'animatemotion',
  animateTransform: 'animatetransform',
  audio: 'audio',
  canvas: 'canvas',
  circle: 'circle',
  clipPath: 'clippath',
  colorProfile: 'color-profile',
  cursor: 'cursor',
  defs: 'defs',
  desc: 'desc',
  discard: 'discard',
  ellipse: 'ellipse',
  feBlend: 'feblend',
  feColorMatrix: 'fecolormatrix',
  feComponentTransfer: 'fecomponenttransfer',
  feComposite: 'fecomposite',
  feConvolveMatrix: 'feconvolvematrix',
  feDiffuseLighting: 'fediffuselighting',
  feDisplacementMap: 'fedisplacementmap',
  feDistantLight: 'fedistantlight',
  feDropShadow: 'fedropshadow',
  feFlood: 'feflood',
  feFuncA: 'fefunca',
  feFuncB: 'fefuncb',
  feFuncG: 'fefuncg',
  feFuncR: 'fefuncr',
  feGaussianBlur: 'fegaussianblur',
  feImage: 'feimage',
  feMerge: 'femerge',
  feMergeNode: 'femergenode',
  feMorphology: 'femorphology',
  feOffset: 'feoffset',
  fePointLight: 'fepointlight',
  feSpecularLighting: 'fespecularlighting',
  feSpotLight: 'fespotlight',
  feTile: 'fetile',
  feTurbulence: 'feturbulence',
  filter: 'filter',
  font: 'font',
  fontFace: 'font-face',
  fontFaceFormat: 'font-face-format',
  fontFaceName: 'font-face-name',
  fontFaceSrc: 'font-face-src',
  fontFaceUri: 'font-face-uri',
  foreignObject: 'foreignobject',
  g: 'g',
  glyph: 'glyph',
  glyphRef: 'glyphref',
  hatch: 'hatch',
  hatchpath: 'hatchpath',
  hkern: 'hkern',
  iframe: 'iframe',
  image: 'image',
  line: 'line',
  linearGradient: 'lineargradient',
  marker: 'marker',
  mask: 'mask',
  mesh: 'mesh',
  meshgradient: 'meshgradient',
  meshpatch: 'meshpatch',
  meshrow: 'meshrow',
  metadata: 'metadata',
  missingGlyph: 'missing-glyph',
  mpath: 'mpath',
  path: 'path',
  pattern: 'pattern',
  polygon: 'polygon',
  polyline: 'polyline',
  radialGradient: 'radialgradient',
  rect: 'rect',
  script: 'script',
  set: 'set',
  solidcolor: 'solidcolor',
  stop: 'stop',
  style: 'style',
  svg: 'svg',
  switch: 'switch',
  symbol: 'symbol',
  text: 'text',
  textPath: 'textpath',
  title: 'title',
  tref: 'tref',
  tspan: 'tspan',
  unknown: 'unknown',
  use: 'use',
  video: 'video',
  view: 'view',
  vkern: 'vkern',
};
