name: 🐞 Bug Report
description: Something does not work or is flaky? let us know!
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! We are always on the lookout for folks interested in becoming active contributors to Mitosis. Given its large surface area, there is a ton of room for any engineer to make a large and sustained impact on the project. 
      
        We invest a ton of time in helping newcomers get onboarded, and teach them how to make changes to the codebase (see the following examples: [#847](https://github.com/BuilderIO/mitosis/issues/847#issuecomment-1307439504), [#372](https://github.com/BuilderIO/mitosis/issues/372#issuecomment-1133471614), [#734](https://github.com/BuilderIO/mitosis/issues/734#issuecomment-1255453702)). 
      
        So consider ticking that "Yes" box below, and we'll do our best to set you up for success. 🙂
  - type: dropdown
    id: help-fix
    validations:
      required: true
    attributes:
      label: I am interested in helping provide a fix!
      description: We will offer whatever guidance you need to contribute :)
      options:
        - "Yes"
        - "No"

  - type: checkboxes
    id: component
    attributes:
      label: Which generators are impacted?
      description: Select all the ones that apply, to the best of your knowledge.
      options:
        - label: All
        - label: Angular
        - label: HTML
        - label: Preact
        - label: Qwik
        - label: React
        - label: React-Native
        - label: Solid
        - label: Stencil
        - label: Svelte
        - label: Vue
        - label: Web components

  - type: input
    id: reproduction_fiddle
    attributes:
      description: A link to a https://mitosis.builder.io/playground playground show-casing the bug
      label: Reproduction case
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: A clear and concise description of what you expected to happen.
      label: Expected Behaviour
    validations:
      required: true

  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual Behaviour
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
    validations:
      required: false
