name: 🐞 Bug Report
description: Something does not work or is flaky? let us know!
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please bear in mind that we are a _very_ small and lean team, and the surface area of Mitosis is fairly large due to the nature of the project. 
        As the tool is in beta and under active development, we ask for your patience and help in contributing to this amazing project. 
        We always do our best to empower folks to contribute substantially to the project and quickly have an impact.
  - type: dropdown
    id: help-fix
    validations:
      required: true
    attributes:
      label: I am interested in helping provide a fix!
      description: We will offer whatever guidance you need to contribute :)
      options:
        - "Yes"
        - "No"

  - type: checkboxes
    id: component
    attributes:
      label: Which generators are impacted?
      description: Select all the ones that apply, to the best of your knowledge.
      options:
        - label: All
        - label: Angular
        - label: HTML
        - label: Qwik
        - label: React
        - label: React-Native
        - label: Solid
        - label: Stencil
        - label: Svelte
        - label: Vue
        - label: Web components

  - type: input
    id: reproduction_fiddle
    attributes:
      description: A link to a https://mitosis.builder.io fiddle show-casing the bug
      label: Reproduction case
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: A clear and concise description of what you expected to happen.
      label: Expected Behaviour
    validations:
      required: true

  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual Behaviour
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
    validations:
      required: false
