name: 🚀 Feature Proposal
description: Suggest an idea for this project
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature proposal! We are always on the lookout for folks interested in becoming active contributors to Mitosis. Given its large surface area, there is a ton of room for any engineer to make a large and sustained impact on the project.
        So consider ticking that "Yes" box below, and we'll do our best to set you up for success. 🙂
  - type: dropdown
    id: help-fix
    validations:
      required: true
    attributes:
      label: I am interested in helping provide a feature!
      description: We will offer whatever guidance you need to contribute :)
      options:
        - "Yes"
        - "No"

  - type: checkboxes
    id: component
    attributes:
      label: Which generators are impacted?
      description: Select all the ones that apply, to the best of your knowledge.
      options:
        - label: All
        - label: Angular
        - label: HTML
        - label: Qwik
        - label: React
        - label: React-Native
        - label: Solid
        - label: Stencil
        - label: Svelte
        - label: Vue
        - label: Web components

  - type: textarea
    id: problem-description
    attributes:
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?“
      label: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposed-API
    attributes:
      label: What does the proposed API look like?
      description: |
        Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
    validations:
      required: false