export const MOCK_DATA = [
  {
    country: 'United Kingdom',
    domains: ['futureworks.ac.uk'],
    web_pages: ['https://futureworks.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Futureworks',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['arts.ac.uk'],
    web_pages: ['https://www.arts.ac.uk'],
    alpha_two_code: 'GB',
    name: 'University of the Arts London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['abdn.ac.uk', 'aberdeen.ac.uk'],
    web_pages: ['http://www.abdn.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Aberdeen',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['aber.ac.uk'],
    web_pages: ['http://www.aber.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales, Aberystwyth',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['abertay.ac.uk'],
    web_pages: ['http://www.abertay.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Abertay Dundee',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['aiuniv.edu'],
    web_pages: ['http://www.aiuniv.edu/'],
    alpha_two_code: 'GB',
    name: 'American InterContinental University - London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['aku.edu'],
    web_pages: ['http://www.aku.edu/'],
    alpha_two_code: 'GB',
    name: 'Aga Khan University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['anglia.ac.uk'],
    web_pages: ['http://www.anglia.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Anglia Ruskin University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['aston.ac.uk'],
    web_pages: ['http://www.aston.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Aston University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['aul.edu'],
    web_pages: ['http://www.aul.edu/'],
    alpha_two_code: 'GB',
    name: 'The American University in London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bangor.ac.uk'],
    web_pages: ['http://www.bangor.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales, Bangor',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bath.ac.uk'],
    web_pages: ['http://www.bath.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Bath',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bathspa.ac.uk'],
    web_pages: ['https://www.bathspa.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Bath Spa University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bbk.ac.uk'],
    web_pages: ['http://www.bbk.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Birkbeck College, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bcom.ac.uk'],
    web_pages: ['http://www.bcom.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'British College of Osteopathic Medicine',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bcu.ac.uk'],
    web_pages: ['http://www.bcu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Birmingham City University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['beds.ac.uk'],
    web_pages: ['http://www.beds.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Bedfordshire',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bham.ac.uk'],
    web_pages: ['http://www.bham.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Birmingham',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bolton.ac.uk'],
    web_pages: ['http://www.bolton.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Bolton',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bournemouth.ac.uk'],
    web_pages: ['http://www.bournemouth.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Bournemouth University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['brad.ac.uk'],
    web_pages: ['http://www.brad.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Bradford',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['brijnet.org'],
    web_pages: ['http://www.brijnet.org/lsjs/'],
    alpha_two_code: 'GB',
    name: 'London School of Jewish Studies',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bris.ac.uk'],
    web_pages: ['http://www.bris.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Bristol',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['brookes.ac.uk'],
    web_pages: ['http://www.brookes.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Oxford Brookes University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['brunel.ac.uk'],
    web_pages: ['http://www.brunel.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Brunel University Uxbridge',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bton.ac.uk'],
    web_pages: ['http://www.bton.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Brighton',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['buck.ac.uk'],
    web_pages: ['http://www.buck.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Buckingham',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['bucks.ac.uk'],
    web_pages: ['http://www.bucks.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Buckinghamshire New University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['cam.ac.uk'],
    web_pages: ['http://www.cam.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Cambridge',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['camb.linst.ac.uk'],
    web_pages: ['http://www.camb.linst.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Camberwell College of Arts',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['canterbury.ac.uk'],
    web_pages: ['http://www.canterbury.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Canterbury Christ Church University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['cardiff.ac.uk', 'cf.ac.uk'],
    web_pages: ['http://www.cardiff.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Cardiff University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['chelsea.linst.ac.uk'],
    web_pages: ['http://www.chelsea.linst.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Chelsea College of Art and Design',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['chester.ac.uk'],
    web_pages: ['http://www.chester.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Chester',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['city.ac.uk'],
    web_pages: ['http://www.city.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'City University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['courtauld.ac.uk'],
    web_pages: ['http://www.courtauld.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Courtauld Institute of Art, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['coventry.ac.uk'],
    web_pages: ['http://www.coventry.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Coventry University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['cranfield.ac.uk'],
    web_pages: ['http://www.cranfield.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Cranfield University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['csm.linst.ac.uk'],
    web_pages: ['http://www.csm.linst.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Central Saint Martins College of Art & Design',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['derby.ac.uk'],
    web_pages: ['http://www.derby.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Derby',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['dmu.ac.uk'],
    web_pages: ['http://www.dmu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'De Montfort University Leicester',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['dundee.ac.uk'],
    web_pages: ['http://www.dundee.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Dundee',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['dur.ac.uk'],
    web_pages: ['http://www.dur.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Durham',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['edgehill.ac.uk'],
    web_pages: ['http://www.edgehill.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Edge Hill University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ed.ac.uk'],
    web_pages: ['http://www.ed.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Edinburgh',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['eselondon.ac.uk'],
    web_pages: ['http://www.eselondon.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'European School of Economics',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['essex.ac.uk', 'sx.ac.uk'],
    web_pages: ['http://www.essex.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Essex',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ex.ac.uk'],
    web_pages: ['http://www.ex.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Exeter',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['falmouth.ac.uk'],
    web_pages: ['http://www.falmouth.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Falmouth University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['gcal.ac.uk', 'gcu.ac.uk'],
    web_pages: ['http://www.gcal.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Glasgow Caledonian University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['gla.ac.uk'],
    web_pages: ['http://www.gla.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Glasgow',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['glam.ac.uk'],
    web_pages: ['http://www.glam.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Glamorgan',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['glos.ac.uk'],
    web_pages: ['http://www.glos.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Gloucestershire',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['gold.ac.uk'],
    web_pages: ['http://www.gold.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Goldsmiths College, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['gre.ac.uk'],
    web_pages: ['http://www.gre.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Greenwich',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['gsa.ac.uk', 'student.gsa.ac.uk'],
    web_pages: ['http://www.gsa.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Glasgow School of Art',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['halifaxuni.ac'],
    web_pages: ['http://www.halifaxuni.ac/'],
    alpha_two_code: 'GB',
    name: 'University of Halifax, Birmingham Campus',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['herts.ac.uk'],
    web_pages: ['http://www.herts.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Hertfordshire',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['heythrop.ac.uk'],
    web_pages: ['http://www.heythrop.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Heythrop College, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['hope.ac.uk'],
    web_pages: ['http://www.hope.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Liverpool Hope University College',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['hud.ac.uk'],
    web_pages: ['http://www.hud.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Huddersfield',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['hull.ac.uk'],
    web_pages: ['http://www.hull.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Hull',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['huron.ac.uk'],
    web_pages: ['http://www.huron.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Huron University USA in London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['hw.ac.uk'],
    web_pages: ['http://www.hw.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Heriot-Watt University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['imperial.ac.uk', 'ic.ac.uk'],
    web_pages: ['http://www.imperial.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Imperial College London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ifslearning.ac.uk'],
    web_pages: ['http://www.ifslearning.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'ifs University College',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ihr.sas.ac.uk'],
    web_pages: ['http://ihr.sas.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Institue of Historical Research, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ihr.sas.ac.uk'],
    web_pages: ['http://www.ihr.sas.ac.uk/ics/'],
    alpha_two_code: 'GB',
    name: 'Institute of Commonwealth Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ioe.ac.uk'],
    web_pages: ['http://www.ioe.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Institute of Education, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['islamiccolleges.com'],
    web_pages: ['http://www.islamiccolleges.com/'],
    alpha_two_code: 'GB',
    name: 'International Colleges of Islamic Science',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['kcl.ac.uk'],
    web_pages: ['http://www.kcl.ac.uk/'],
    alpha_two_code: 'GB',
    name: "King's College London, University of London",
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['keele.ac.uk'],
    web_pages: ['http://www.keele.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Keele University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['kingston.ac.uk'],
    web_pages: ['http://www.kingston.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Kingston University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['kolieh.com'],
    web_pages: ['http://www.kolieh.com/'],
    alpha_two_code: 'GB',
    name: 'International Centre for Isclamic Science',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lamp.ac.uk'],
    web_pages: ['http://www.lamp.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales, Lampeter',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lancs.ac.uk'],
    web_pages: ['http://www.lancs.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Lancaster',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lboro.ac.uk', 'student.lboro.ac.uk'],
    web_pages: ['http://www.lboro.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Loughborough University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lbs.lon.ac.uk'],
    web_pages: ['http://www.lbs.lon.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'London Business School',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lcst.ac'],
    web_pages: ['http://www.lcst.ac/'],
    alpha_two_code: 'GB',
    name: 'London College of Science & Technology',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['le.ac.uk'],
    web_pages: ['http://www.le.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Leicester',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['leeds.ac.uk'],
    web_pages: ['http://www.leeds.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Leeds',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lgu.ac.uk'],
    web_pages: ['http://www.lgu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'London Guildhall University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['limt.co.uk'],
    web_pages: ['http://www.limt.co.uk/'],
    alpha_two_code: 'GB',
    name: 'London Institute of Management and Technology',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lincoln.ac.uk'],
    web_pages: ['http://www.lincoln.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Lincoln',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['liv.ac.uk'],
    web_pages: ['http://www.liv.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Liverpool',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ljmu.ac.uk'],
    web_pages: ['https://www.ljmu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Liverpool John Moores University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lmu.ac.uk'],
    web_pages: ['http://www.lmu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Leeds Metropolitan University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lon.ac.uk'],
    web_pages: ['http://www.lon.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['londonmet.ac.uk'],
    web_pages: ['http://www.londonmet.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'London Metropolitan University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lsbf.org.uk'],
    web_pages: ['http://www.lsbf.org.uk/'],
    alpha_two_code: 'GB',
    name: 'London School of Business & Finance',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lse.ac.uk'],
    web_pages: ['http://www.lse.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'London School of Economics and Political Science, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['lshtm.ac.uk'],
    web_pages: ['http://www.lshtm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'London School of Hygiene & Tropical Medicine, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['manchester.ac.uk', 'mbs.ac.uk', 'man.ac.uk'],
    web_pages: ['http://www.manchester.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Manchester',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['mdx.ac.uk'],
    web_pages: ['http://www.mdx.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Middlesex University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['med.ic.ac.uk'],
    web_pages: ['http://www.med.ic.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Imperial College School of Medicine',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['mmu.ac.uk'],
    web_pages: ['http://www.mmu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'The Manchester Metropolitan University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['napier.ac.uk'],
    web_pages: ['http://www.napier.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Napier University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ncl.ac.uk'],
    web_pages: ['http://www.ncl.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Newcastle-upon-Tyne',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['newport.ac.uk'],
    web_pages: ['http://www.newport.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales, Newport',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['niu.org.uk'],
    web_pages: ['http://www.niu.org.uk/'],
    alpha_two_code: 'GB',
    name: 'Newport International University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['northampton.ac.uk'],
    web_pages: ['http://www.northampton.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Northampton',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['nottingham.ac.uk'],
    web_pages: ['http://www.nottingham.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Nottingham',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ntu.ac.uk'],
    web_pages: ['http://www.ntu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Nottingham Trent University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['open.ac.uk'],
    web_pages: ['http://www.open.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Open University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['oxford.ac.uk', 'ox.ac.uk'],
    web_pages: ['http://www.ox.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Oxford',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['paisley.ac.uk'],
    web_pages: ['http://www.paisley.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Paisley',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['plymouth.ac.uk'],
    web_pages: ['http://www.plymouth.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Plymouth',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['port.ac.uk'],
    web_pages: ['http://www.port.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Portsmouth',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['qmw.ac.uk', 'qmul.ac.uk'],
    web_pages: ['http://www.qmul.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Queen Mary, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['qub.ac.uk'],
    web_pages: ['http://www.qub.ac.uk/'],
    alpha_two_code: 'GB',
    name: "The Queen's University Belfast",
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ram.ac.uk'],
    web_pages: ['http://www.ram.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Royal Academy of Music, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['rca.ac.uk', 'network.rca.ac.uk'],
    web_pages: ['http://www.rca.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Royal College of Art',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['rcm.ac.uk'],
    web_pages: ['http://www.rcm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Royal College of Music, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['rdg.ac.uk'],
    web_pages: ['http://www.rdg.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Reading',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['rfhsm.ac.uk'],
    web_pages: ['http://www.rfhsm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Royal Free Hospital School of Medicine, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['rgu.ac.uk'],
    web_pages: ['http://www.rgu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'The Robert Gordon University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['royalholloway.ac.uk', 'rhbnc.ac.uk', 'rh.ac.uk'],
    web_pages: ['http://www.royalholloway.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Royal Holloway and Bedford New College',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['richmond.ac.uk'],
    web_pages: ['http://www.richmond.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Richmond University - The American International University in London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['roehampton.ac.uk'],
    web_pages: ['http://www.roehampton.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Roehampton University of Surrey',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['salford.ac.uk'],
    web_pages: ['http://www.salford.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Salford',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sas.ac.uk'],
    web_pages: ['http://www.sas.ac.uk/ials/'],
    alpha_two_code: 'GB',
    name: 'Institute of Advanced Legal Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sas.ac.uk'],
    web_pages: ['http://www.sas.ac.uk/icls/'],
    alpha_two_code: 'GB',
    name: 'Institute of Classical Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sas.ac.uk'],
    web_pages: ['http://www.sas.ac.uk/igs/'],
    alpha_two_code: 'GB',
    name: 'Institute of Germanic Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sas.ac.uk'],
    web_pages: ['http://www.sas.ac.uk/ilas/'],
    alpha_two_code: 'GB',
    name: 'Institute of Latin American Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sas.ac.uk'],
    web_pages: ['http://www.sas.ac.uk/warburg/'],
    alpha_two_code: 'GB',
    name: 'Warburg Institute, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sbu.ac.uk'],
    web_pages: ['http://www.sbu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'South Bank University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['schillerlondon.ac.uk'],
    web_pages: ['http://www.schillerlondon.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Schiller International University, London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sclondon.ac'],
    web_pages: ['http://www.sclondon.ac/'],
    alpha_two_code: 'GB',
    name: 'Stratford College London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sghms.ac.uk'],
    web_pages: ['http://www.sghms.ac.uk/'],
    alpha_two_code: 'GB',
    name: "Saint George's Hospital Medical School, University of London",
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['shef.ac.uk', 'sheffield.ac.uk'],
    web_pages: ['http://www.shef.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Sheffield',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['shu.ac.uk'],
    web_pages: ['http://www.shu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Sheffield Hallam University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['smu.ac.uk'],
    web_pages: ['http://www.smu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Swansea Metropolitan University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['soas.ac.uk'],
    web_pages: ['http://www.soas.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'School of Oriental and African Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['solent.ac.uk'],
    web_pages: ['http://www.solent.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Southampton Solent University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sothebysinstitutelondon.com'],
    web_pages: ['http://www.sothebysinstitutelondon.com/'],
    alpha_two_code: 'GB',
    name: 'Sotheby´s Institute of Art - London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['soton.ac.uk'],
    web_pages: ['http://www.southampton.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Southampton',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ssees.ac.uk'],
    web_pages: ['http://www.ssees.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'School of Slavonic and East European Studies, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['staffs.ac.uk'],
    web_pages: ['http://www.staffs.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Staffordshire University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['st-andrews.ac.uk', 'st-and.ac.uk'],
    web_pages: ['https://www.st-andrews.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of St. Andrews',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['stir.ac.uk'],
    web_pages: ['http://www.stir.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Stirling',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['st-patricks.ac.uk'],
    web_pages: ['http://www.st-patricks.ac.uk/'],
    alpha_two_code: 'GB',
    name: "St.Patrick's International College, London",
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['strath.ac.uk'],
    web_pages: ['http://www.strath.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Strathclyde',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sunderland.ac.uk'],
    web_pages: ['http://www.sunderland.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Sunderland',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['surrey.ac.uk'],
    web_pages: ['http://www.surrey.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Surrey',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['sussex.ac.uk'],
    web_pages: ['http://www.sussex.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Sussex',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['swan.ac.uk'],
    web_pages: ['http://www.swan.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales, Swansea',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['tcm.ac.uk'],
    web_pages: ['http://www.tcm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Trinity College of Music',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['tees.ac.uk'],
    web_pages: ['http://www.tees.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Teesside',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['trinity-cm.ac.uk'],
    web_pages: ['http://www.trinity-cm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Trinity College Carmarthen',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['tvu.ac.uk'],
    web_pages: ['http://www.tvu.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Thames Valley University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ucl.ac.uk'],
    web_pages: ['http://www.ucl.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University College London, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uclan.ac.uk'],
    web_pages: ['http://www.uclan.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Central Lancashire',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ucs.ac.uk'],
    web_pages: ['http://www.ucs.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University Campus Suffolk',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uea.ac.uk'],
    web_pages: ['http://www.uea.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of East Anglia',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uel.ac.uk'],
    web_pages: ['http://www.uel.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of East London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ukc.ac.uk'],
    web_pages: ['http://www.ukc.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Kent at Canterbury',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ulsop.ac.uk'],
    web_pages: ['http://www.ulsop.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'School of Pharmacy, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['ulst.ac.uk'],
    web_pages: ['http://www.ulst.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Ulster',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['umds.ac.uk'],
    web_pages: ['http://www.umds.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'United Medical and Dental Schools, University of London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['unl.ac.uk'],
    web_pages: ['http://www.unl.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of North London',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['unn.ac.uk'],
    web_pages: ['http://www.unn.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Northumbria at Newcastle',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uwcm.ac.uk'],
    web_pages: ['http://www.uwcm.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales College of Medicine',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uwe.ac.uk'],
    web_pages: ['http://www.uwe.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of the West of England, Bristol',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['uwic.ac.uk'],
    web_pages: ['http://www.uwic.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales Institute, Cardiff',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['wales.ac.uk'],
    web_pages: ['http://www.wales.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wales',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['warnborough.edu'],
    web_pages: ['http://www.warnborough.edu/'],
    alpha_two_code: 'GB',
    name: 'Warnborough University',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['warwick.ac.uk'],
    web_pages: ['http://www.warwick.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Warwick',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['westminster.ac.uk'],
    web_pages: ['http://www.westminster.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Westminster',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['williamgilbert.co.uk'],
    web_pages: ['http://www.williamgilbert.co.uk/'],
    alpha_two_code: 'GB',
    name: 'William Gilbert College',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['wimbledon.ac.uk'],
    web_pages: ['http://www.wimbledon.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Wimbledon School of Art',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['wlv.ac.uk'],
    web_pages: ['http://www.wlv.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Wolverhampton',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['worc.ac.uk'],
    web_pages: ['http://www.worc.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of Worcester',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['york.ac.uk'],
    web_pages: ['http://www.york.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'University of York',
    'state-province': null,
  },
  {
    country: 'United Kingdom',
    domains: ['middlesbro.ac.uk', 'mbro.ac.uk'],
    web_pages: ['https://www.mbro.ac.uk/'],
    alpha_two_code: 'GB',
    name: 'Middlesbrough College',
    'state-province': null,
  },
];
