name: Crawl the docs site with Meilisearch Cloud to update the contents to the latest

on: [push]

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: meilisearch/actions/cloud-crawler@main
        with:
          token: ${{ secrets.MEILISEARCH_CLOUD_CRAWLER_TOKEN }}
