name: Save artifact on branch push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn ci:build

      - name: Run tests
        run: yarn ci:test

      - name: Run prettier
        run: yarn ci:lint

      - name: Install browsers for Playwright
        run: yarn ci:e2e-prep

      - name: Run E2E tests
        run: yarn ci:e2e

      - name: save artifact
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        if: "${{ env.API_TOKEN_GITHUB != '' }}"
        run: yarn workspace @builder.io/mitosis run mitosis-save-artifacts
