name: Save artifact on branch push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: build
        run: yarn workspace @builder.io/mitosis run build

      - name: save artifact
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: yarn workspace @builder.io/mitosis run mitosis-save-artifacts
