---
name: PR Runner

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      # Adding Bazel cache seems to cause issues. Disabling for now, until we can investigate
      # - name: Mount bazel cache
      #   uses: actions/cache@v2
      #   with:
      #     path: '~/.cache/bazel'
      #     key: bazel

      - name: Build all targets
        run: bazel build //...

      - name: Run all tests
        run: echo No Tests to run yet # bazel test //...

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        id: restore-node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install
          npx lerna bootstrap

      - name: Run prettier
        run: npm run ci:lint

      - name: Run tests
        run: npm run ci:test

      - name: Build
        run: npm run ci:build
