---
name: PR Runner

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn ci:build

      - name: Run tests
        run: yarn ci:test

      - name: Run prettier
        run: yarn ci:lint

      - name: Install browsers for Playwright
        run: yarn ci:e2e-prep

      - name: Build E2E tests
        run: yarn ci:e2e-build

      - name: Run E2E tests
        run: yarn ci:e2e
