name: PR Runner
on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install and run prettier
        run: npm install && npm run prettier -- --check .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install and run prettier
        run: npm install && cd packages/core && npm install && npm run test
