# This workflow runs when new change is pushed to the main repo.
# It should only save artifacts and nothing else so that it is fast.

name: Save artifact on branch push

on:
  push:

jobs:
  save-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn ci:build

      - name: save artifact
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        if: "${{ env.API_TOKEN_GITHUB != '' }}"
        run: yarn workspace @builder.io/mitosis run mitosis-save-artifacts
